name: Report a sync error
description: Flag an improprerly synced identifier(s) in one of our public datasets.
title: "[Sync Error]: "
labels: ["sync-error"]

type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report issues with our datasets! Ensuring that these identifiers are accurate makes these public resources as useful and reliable as possible for analysis.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: competition
    attributes:
      label: Competition
      description: Which competition had data sync error(s)?
      options:
        - Major League Soccer (MLS)
        - National Women's Soccer League (NWSL)
        - USL Super League
      default: 0
    validations:
      required: true
  - type: dropdown
    id: season
    attributes:
      label: Season
      description: Which season had data sync error(s)?
      options:
        - 2025
      default: 0
    validations:
      required: true
  - type: dropdown
    id: dataset
    attributes:
      label: Dataset
      description: Which dataset had data sync error(s)?
      options:
        - Player
        - Team
        - Match
      default: 0
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Relevant corrections
      description: |
        Please explain what corrections need to be made, including:
          - What object needs an update? (Player Name, Match Date/Teams, Team Name)
          - Which provider's ID needs to be updated? What does it need to be updated to?
    validations:
      required: true